foo: bar
file: |
  hello: world
  question:
    - what
    - is
    - the
    - answer
timeout: 10s
people: alice,bob,carol
date: 2019-01-01T00:00:00+08:00
when: 2023-02-03T04:05:06+07:00
file2: |
  hello: world
  question:
    - what
    - is
    - the
    - answer
file3: |
  - name: alice
    age: 18
  - name: bob
    age: 19
  - name: carol
    age: 20